### ISSUE TITLE
Generate favicon.png while you're at it

### ISSUE THREAD

**Issue by codyburleson** [pverhaert/ngx-pwa-icons#1]
Please provide option to also generate `favicon.png` (for me, that's in `src/assets/icon`).

**Comment by pverhaert** [comment]
Cody,
- Remove ngx-pwa-icons: `npm rm -g ngx-pwa-icons`
- Install new version (0.1.1): `npm i -g ngx-pwa-icons`
- (Check version: `ngx-pwa-icons -v`)
- Run:  `ngx-pwa-icons -o "./src/assets/icon" -n "favicon.png" -s 32`

**Comment by codyburleson** [comment]
Oh, sorry. Confirmed a while ago! Works like a charm now. Thanks for the quick turnaround and support!
